CASES=[]

def add(cat,cid,text,expected,ctx=None):
    CASES.append({"category":cat,"id":cid,"text":text,"ctx":ctx or {},"expected":expected if isinstance(expected,list) else [expected]})
def do(op,args=None): return {"route":"do","op":op,"args":args or {}}
def ask(): return {"route":"ask"}
def think(): return {"route":"think"}

# Camera / viewer — 14
add("camera","v09_c01","یه ذره بچرخونش به راست",do("view.move",{"action":"orbit","direction":"right"}))
add("camera","v09_c02","یه خورده بچرخونش سمت چپ",do("view.move",{"action":"orbit","direction":"left"}))
add("camera","v09_c03","یه کوچولو در جهت عقربه ها بچرخونش",do("view.move",{"action":"orbit","direction":"clockwise"}))
add("camera","v09_c04","برعکس عقربه ها یه ذره بچرخون",do("view.move",{"action":"orbit","direction":"counterclockwise"}))
add("camera","v09_c05","سی درجه به راست بچرخونش",do("view.move",{"action":"orbit","direction":"right","angle_degrees":30}))
add("camera","v09_c06","نمای کار رو یه کم بکش بالا",do("view.move",{"action":"pan","direction":"up"}))
add("camera","v09_c07","کل صفحه رو یه ذره بده سمت چپ",do("view.move",{"action":"pan","direction":"left"}))
add("camera","v09_c08","یه پله نزدیک تر شو",do("view.move",{"action":"zoom","direction":"in"}))
add("camera","v09_c09","یه پله دورتر شو",do("view.move",{"action":"zoom","direction":"out"}))
add("camera","v09_c10","یه کاری کن همه مدل معلوم باشه",do("view.fit",{"action":"fit"}))
add("camera","v09_c11","فقط همین انتخاب بزرگ شه تو صفحه",do("view.fit",{"action":"fit_selection"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("camera","v09_c12","از بالا ببینیمش",do("view.standard",{"view":"top"}))
add("camera","v09_c13","هر چی الان انتخابه پاکش کن",do("viewer.selection.clear",{}))
add("camera","v09_c14","نمای جلو رو بده",ask())

# Inspect / follow — 8
add("inspect","v09_i01","الان چی دستمه؟",do("viewer.inspect",{"mode":"selection"}))
add("inspect","v09_i02","وضعیت صفحه رو یه نگاه بنداز",do("viewer.inspect",{"mode":"state"}))
add("inspect","v09_i03","ببین کیا الان وصلن",do("viewer.inspect",{"mode":"collaboration"}))
add("inspect","v09_i04","اون یکی که وصله رو دنبال کن",do("view.follow",{}),{"collaborator_count":2})
add("inspect","v09_i05","دومی رو فالو کن",do("view.follow",{"candidate_index":2}),{"collaborator_count":3})
add("inspect","v09_i06","یکی از این سه نفر رو فالو کن",ask(),{"collaborator_count":3})
add("inspect","v09_i07","همین سطحی که روشم هستم رو بگیر",ask())
add("inspect","v09_i08","کنار این یکی یه انتخاب دیگه هم بزن",ask(),{"selection_count":1})

# Edge / current selection — 14
add("edge","v09_e01","روی همین انتخاب فیلت یک و دو دهم میل بزن",do("feature.from_selection",{"feature_type":"fillet","amount":"1.2 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v09_e02","لبه های انتخابی رو هفتاد و پنج صدم میل پخ بزن",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.75 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v09_e03","این لبه ها رو دو و نیم میل گرد کن",do("feature.from_selection",{"feature_type":"fillet","amount":"2.5 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v09_e04","لبه ها رو یک و بیست صدم میلی چمفر کن",do("feature.from_selection",{"feature_type":"chamfer","amount":"1.2 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v09_e05","روی همین انتخاب چمفر نیم میل بزن",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.5 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v09_e06","این یکی رو فیلت سه دهم بزن",do("feature.from_selection",{"feature_type":"fillet","amount":"0.3 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v09_e07","فیلت بزن روش",ask(),{"selection_count":1,"selection_types":["edge"]})
add("edge","v09_e08","یک میل پخ بزن",ask(),{"selection_count":0})
add("edge","v09_e09","یه فیلت تازه سه میلی بساز فعلا بی لبه",do("feature.add",{"feature_type":"fillet","amount":"3 mm"}))
add("edge","v09_e10","یه چمفر خالی شش دهم میل بساز",do("feature.add",{"feature_type":"chamfer","amount":"0.6 mm"}))
add("edge","v09_e11","اول دو میل فیلت کن بعد یک میل پخ",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v09_e12","این لبه رو فیلت کن بعد پارتی که روشه رو قایم کن",ask(),{"selection_count":1,"selection_types":["edge"],"last_part":"Part 3"})
add("edge","v09_e13","یه خورده فیلتش کن",ask(),{"selection_count":1,"selection_types":["edge"]})
add("edge","v09_e14","همین لبه ها رو پخ یک میل و نیم",do("feature.from_selection",{"feature_type":"chamfer","amount":"1.5 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})

# Existing feature edits — 18
add("feature","v09_f01","شعاع Fillet 5 رو بذار نه میل",do("feature.parameter.set",{"feature_name":"Fillet 5","parameter":"radius","amount":"9 mm"}))
add("feature","v09_f02","عمق Extrude 7 رو بیست و دو میل کن",do("feature.parameter.set",{"feature_name":"Extrude 7","parameter":"depth","amount":"22 mm"}))
add("feature","v09_f03","Extrude 7 رو بیست و دو میل کن",ask())
add("feature","v09_f04","زاویه Draft 4 رو دوازده درجه کن",do("feature.parameter.set",{"feature_name":"Draft 4","parameter":"angle","amount":"12 deg"}))
add("feature","v09_f05","این فیلت رو نیم میل زیادش کن",do("feature.parameter.set",{"feature_name":"Fillet 2","parameter":"radius","amount":"4.5 mm"}),{"last_feature":"Fillet 2","feature_parameters":{"radius":"4 mm"}})
add("feature","v09_f06","این فیلت رو یک و بیست و پنج صدم میل کم کن",do("feature.parameter.set",{"feature_name":"Fillet 3","parameter":"radius","amount":"4.75 mm"}),{"last_feature":"Fillet 3","feature_parameters":{"radius":"6 mm"}})
add("feature","v09_f07","یه کوچولو بیشترش کن",ask(),{"last_feature":"Extrude 3","feature_parameters":{"depth":"12 mm"}})
add("feature","v09_f08","Extrude 8 رو فعلا خاموشش کن",do("feature.patch",{"feature_name":"Extrude 8","suppressed":True}))
add("feature","v09_f09","همون Extrude 8 رو دوباره روشنش کن",do("feature.patch",{"feature_name":"Extrude 8","suppressed":False}))
add("feature","v09_f10","اسم Fillet 8 رو بذار edge round",do("feature.patch",{"feature_name":"Fillet 8","new_name":"edge round"}))
add("feature","v09_f11","اسم Fillet 9 رو بذار fit hide check",do("feature.patch",{"feature_name":"Fillet 9","new_name":"fit hide check"}))
add("feature","v09_f12","Extrude 9 رو بنداز دور",do("feature.delete",{"feature_name":"Extrude 9"}))
add("feature","v09_f13","آخرین چیزی که ساختیم رو از فیچرها پاک کن",do("feature.delete",{"position":"last"}))
add("feature","v09_f14","اولین فیچر رو کلا حذف کن",do("feature.delete",{"position":"first"}))
add("feature","v09_f15","flip direction برای Extrude 5 روشن باشه",do("feature.parameter.set",{"feature_name":"Extrude 5","parameter":"flip direction","value":True}))
add("feature","v09_f16","flip direction برای Extrude 5 خاموش باشه",do("feature.parameter.set",{"feature_name":"Extrude 5","parameter":"flip direction","value":False}))
add("feature","v09_f17","شعاع این فیلت رو دو برابر کن",ask(),{"last_feature":"Fillet 4","feature_parameters":{"radius":"3 mm"}})
add("feature","v09_f18","زاویه Draft 2 رو یه کم بیشتر کن",ask())

# Parts / metadata — 14
add("part","v09_p01","Part 4 رو از جلوی چشم بردار",do("part.visibility",{"part_name":"Part 4","visible":False}))
add("part","v09_p02","همون پارت رو دوباره برگردون تو نما",do("part.visibility",{"part_name":"Part 4","visible":True}),{"last_part":"Part 4","last_action":"hide"})
add("part","v09_p03","Part 4 دیگه دیده نشه",do("part.visibility",{"part_name":"Part 4","visible":False}))
add("part","v09_p04","Cap رو سفیدش کن",do("metadata.property.set",{"part_name":"Cap","property":"color","value":"white"}))
add("part","v09_p05","Part 6 رو آبی کن",do("metadata.property.set",{"part_name":"Part 6","property":"color","value":"blue"}))
add("part","v09_p06","اسم Part 8 بشه base",do("metadata.property.set",{"part_name":"Part 8","property":"name","value":"base"}))
add("part","v09_p07","متریال Part 5 رو فولاد بذار",do("metadata.property.set",{"part_name":"Part 5","property":"material","value":"Steel"}))
add("part","v09_p08","Part 6 رو آلومینیوم متریال بده",do("metadata.property.set",{"part_name":"Part 6","property":"material","value":"Aluminum"}))
add("part","v09_p09","description Part 3 رو بذار inner body",do("metadata.property.set",{"part_name":"Part 3","property":"description","value":"inner body"}))
add("part","v09_p10","Part 10 رو کامل حذف کن",do("feature.delete_part",{"part_name":"Part 10"}))
add("part","v09_p11","این قطعه رو پاک کن",do("feature.delete_part",{"part_name":"Part 7"}),{"last_part":"Part 7"})
add("part","v09_p12","Part 2 رو زرد کن و قایمش کن",ask())
add("part","v09_p13","اسم همین پارت رو عوض کن",ask(),{"last_part":"Part 2"})
add("part","v09_p14","Cap رو فقط مخفی کن، رنگش دست نخوره",do("part.visibility",{"part_name":"Cap","visible":False}))

# Create / order / document — 16
add("doc","v09_d01","یه صفحه مرجع خالی برام بساز",do("feature.add",{"feature_type":"plane"}))
add("doc","v09_d02","یه plane بساز اسمش fit plane",do("feature.add",{"feature_type":"plane","name":"fit plane"}))
add("doc","v09_d03","یه plane روی Front دربیار",ask())
add("doc","v09_d04","از Part 2 یه pattern سه تایی با فاصله چهارده میل بساز",do("feature.add",{"feature_type":"linearPattern","part_name":"Part 2","copies":3,"distance":"14 mm"}))
add("doc","v09_d05","Part 3 رو هفت تا خطی تکرار کن، گام چهار میل",do("feature.add",{"feature_type":"linearPattern","part_name":"Part 3","copies":7,"distance":"4 mm"}))
add("doc","v09_d06","Part 2 رو سه تا کن هر چهارده میل",ask())
add("doc","v09_d07","یه fillet خالی دو و دو دهم میل بساز",do("feature.add",{"feature_type":"fillet","amount":"2.2 mm"}))
add("doc","v09_d08","یه chamfer تازه نه دهم میل بدون لبه بساز",do("feature.add",{"feature_type":"chamfer","amount":"0.9 mm"}))
add("doc","v09_d09","Fillet 2 رو قبل Extrude 8 بذار",do("feature.reorder",{"source_feature":"Fillet 2","target_feature":"Extrude 8","placement":"before"}))
add("doc","v09_d10","Extrude 8 رو ببر زیر Sketch 5",do("feature.reorder",{"source_feature":"Extrude 8","target_feature":"Sketch 5","placement":"after"}))
add("doc","v09_d11","همینو ببر قبل Fillet 10",do("feature.reorder",{"source_feature":"Extrude 4","target_feature":"Fillet 10","placement":"before"}),{"last_feature":"Extrude 4"})
add("doc","v09_d12","rollback رو درست قبل Extrude 6 نگه دار",do("rollback.set",{"before_feature":"Extrude 6"}))
add("doc","v09_d13","rollback رو بنداز بعد Fillet 3",do("rollback.set",{"after_feature":"Fillet 3"}))
add("doc","v09_d14","rollback رو ببر اول کار",do("rollback.set",{"position":"start"}))
add("doc","v09_d15","یه تب Part Studio تازه بساز به اسم mockup",do("documented.createPartStudio",{"new_name":"mockup"}))
add("doc","v09_d16","اسم فایل رو بذار suitcase rev C",do("documented.updateDocumentAttributes",{"new_name":"suitcase rev C"}))

# Open-ended / ambiguity / unsupported — 16
add("escalate","v09_x01","این قسمت رو یه جوری قوی تر کن که تاب برنداره",think())
add("escalate","v09_x02","ضخامت رو کمتر کن ولی ضعیف نشه",think())
add("escalate","v09_x03","این قطعه رو برای قالب تزریق منطقی ترش کن",think())
add("escalate","v09_x04","درخت فیچر خیلی شلوغه، مرتبش کن",think())
add("escalate","v09_x05","این گوشه رو بهتر دربیار که تمیزتر بشه",think())
add("escalate","v09_x06","اون یکی رو پاک کن",ask())
add("escalate","v09_x07","پنج میلش کن",ask())
add("escalate","v09_x08","همون کار قبلی رو اینجا هم تکرار کن",ask())
add("escalate","v09_x09","ازش STEP خروجی بگیر",ask())
add("escalate","v09_x10","با علی share کن",ask())
add("escalate","v09_x11","همه بتونن ببیننش، publicش کن",ask())
add("escalate","v09_x12","یه سوراخ اینجا بزن",ask())
add("escalate","v09_x13","این دوتا رو نسبت به هم mirror کن",ask())
add("escalate","v09_x14","همه پارت ها رو خاکستری کن",ask())
add("escalate","v09_x15","هر چی فیلت اضافیه جمعش کن",think())
add("escalate","v09_x16","این قسمت رو جمع و جورتر کن که توی قاب جا بگیره",think())

assert len(CASES)==100, len(CASES)
