CASES=[]

def add(cat,cid,text,expected,ctx=None):
    CASES.append({"category":cat,"id":cid,"text":text,"ctx":ctx or {},"expected":expected if isinstance(expected,list) else [expected]})
def do(op,args=None): return {"route":"do","op":op,"args":args or {}}
def ask(): return {"route":"ask"}
def think(): return {"route":"think"}

# camera/viewer 18
add("camera","v12_c01","یه کم مدل رو بنداز سمت راست",do("view.move",{"action":"orbit","direction":"right"}))
add("camera","v12_c02","یکم rotate کن به چپ",do("view.move",{"action":"orbit","direction":"left"}))
add("camera","v12_c03","یه ذره با جهت عقربه ها بچرخون",do("view.move",{"action":"orbit","direction":"clockwise"}))
add("camera","v12_c04","یه ذره خلاف عقربه ها بچرخون",do("view.move",{"action":"orbit","direction":"counterclockwise"}))
add("camera","v12_c05","بیست و پنج درجه سمت چپ بچرخون",do("view.move",{"action":"orbit","direction":"left","angle_degrees":25}))
add("camera","v12_c06","ربع دور به راست ببرش",do("view.move",{"action":"orbit","direction":"right","angle_degrees":90}))
add("camera","v12_c07","نما رو کمی بکش سمت چپ",do("view.move",{"action":"pan","direction":"left"}))
add("camera","v12_c08","صفحه رو یه خورده بکش بالا",do("view.move",{"action":"pan","direction":"up"}))
add("camera","v12_c09","pan down یه کوچولو",do("view.move",{"action":"pan","direction":"down"}))
add("camera","v12_c10","یه قدم زوم کن داخل",do("view.move",{"action":"zoom","direction":"in"}))
add("camera","v12_c11","یه قدم ازش دور شو",do("view.move",{"action":"zoom","direction":"out"}))
add("camera","v12_c12","کل مدل رو جوری بیار که کامل دیده بشه",do("view.fit",{"action":"fit"}))
add("camera","v12_c13","فقط انتخابم رو تو صفحه جا بده",do("view.fit",{"action":"fit_selection"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("camera","v12_c14","نمای top رو بده",do("view.standard",{"view":"top"}))
add("camera","v12_c15","selection رو کامل خالی کن",do("viewer.selection.clear",{}))
add("camera","v12_c16","نمای جلو رو نشون بده",ask())
add("camera","v12_c17","یه نمای سه بعدی استاندارد بده",ask())
add("camera","v12_c18","همین انتخابم توی صفحه کامل معلوم باشه",do("view.fit",{"action":"fit_selection"}),{"selection_count":1,"selection_types":["face"]})

# inspect/follow 10
add("inspect","v12_i01","الان چی انتخاب کردم؟",do("viewer.inspect",{"mode":"selection"}))
add("inspect","v12_i02","بگو چی الان دستمه",do("viewer.inspect",{"mode":"selection"}))
add("inspect","v12_i03","وضعیت خود viewer رو چک کن",do("viewer.inspect",{"mode":"state"}))
add("inspect","v12_i04","ببین الان چند نفر وصل هستن",do("viewer.inspect",{"mode":"collaboration"}))
add("inspect","v12_i05","توی این session چند نفریم؟",do("viewer.inspect",{"mode":"collaboration"}))
add("inspect","v12_i06","اون طرف مقابلم رو دنبال کن",do("view.follow",{}),{"collaborator_count":2})
add("inspect","v12_i07","نفر دوم رو follow کن",do("view.follow",{"candidate_index":2}),{"collaborator_count":3})
add("inspect","v12_i08","یکی از سه نفر رو follow کن",ask(),{"collaborator_count":4})
add("inspect","v12_i09","همین چیزی که موس روشه رو انتخاب کن",ask())
add("inspect","v12_i10","یه لبه از سمت راست بردار",ask())

# edge work 18
add("edge","v12_e01","روی این لبه ها فیلت یک و چهار دهم میل بزن",do("feature.from_selection",{"feature_type":"fillet","amount":"1.4 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v12_e02","این انتخاب رو پنجاه و پنج صدم میل پخ کن",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.55 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v12_e03","همین دوتا لبه رو دو میل و نیم فیلت کن",do("feature.from_selection",{"feature_type":"fillet","amount":"2.5 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v12_e04","پخ یک ممیز شش میل روی همین انتخاب",do("feature.from_selection",{"feature_type":"chamfer","amount":"1.6 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v12_e05","فیلت دو و چهل صدم میلی روی اینا",do("feature.from_selection",{"feature_type":"fillet","amount":"2.4 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v12_e06","پخ شش دهم روی انتخاب فعلی",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.6 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v12_e07","روی این لبه ها 1.25 mm fillet بزن",do("feature.from_selection",{"feature_type":"fillet","amount":"1.25 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v12_e08","پخ نیم میلی روی همین لبه",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.5 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v12_e09","سه میل فیلت بزن",ask(),{"selection_count":0})
add("edge","v12_e10","روی انتخاب فعلی پخ بزن",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v12_e11","یه fillet خالی دو و نیم میل درست کن",do("feature.add",{"feature_type":"fillet","amount":"2.5 mm"}))
add("edge","v12_e12","یه chamfer جدید شش دهم میل بدون انتخاب بساز",do("feature.add",{"feature_type":"chamfer","amount":"0.6 mm"}))
add("edge","v12_e13","اول دو میل فیلت بعد یه میل پخ",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v12_e14","فیلتش کن و همزمان سبزش کن",ask(),{"selection_count":1,"selection_types":["edge"],"last_part":"Part 2"})
add("edge","v12_e15","دو میل radius روی این لبه ها بده",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v12_e16","چمفر سه",ask(),{"selection_count":1,"selection_types":["edge"]})
add("edge","v12_e17","پخ دو ممیز پنج میل روی انتخاب",do("feature.from_selection",{"feature_type":"chamfer","amount":"2.5 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v12_e18","یه فیلت خالی ۰.۲۵ میلی بساز",do("feature.add",{"feature_type":"fillet","amount":"0.25 mm"}))

# feature edits 18
add("feature","v12_f01","radius Fillet 4 رو پنج میل کن",do("feature.parameter.set",{"feature_name":"Fillet 4","parameter":"radius","amount":"5 mm"}))
add("feature","v12_f02","عمق Extrude 6 رو شانزده میل کن",do("feature.parameter.set",{"feature_name":"Extrude 6","parameter":"depth","amount":"16 mm"}))
add("feature","v12_f03","Extrude 6 رو شانزده میل کن",ask())
add("feature","v12_f04","زاویه Draft 4 رو هشت درجه کن",do("feature.parameter.set",{"feature_name":"Draft 4","parameter":"angle","amount":"8 deg"}))
add("feature","v12_f05","زاویه Extrude 6 رو هشت درجه کن",ask())
add("feature","v12_f06","عمق Draft 4 رو ده میل کن",ask())
add("feature","v12_f07","شعاع Extrude 6 رو چهار میل کن",ask())
add("feature","v12_f08","این فیلت رو یک و نیم میل بیشتر کن",do("feature.parameter.set",{"feature_name":"Fillet 4","parameter":"radius","amount":"5.5 mm"}),{"last_feature":"Fillet 4","feature_parameters":{"radius":"4 mm"}})
add("feature","v12_f09","این فیلت رو پنجاه صدم میل کمتر کن",do("feature.parameter.set",{"feature_name":"Fillet 4","parameter":"radius","amount":"3.5 mm"}),{"last_feature":"Fillet 4","feature_parameters":{"radius":"4 mm"}})
add("feature","v12_f10","این اکسترود رو یه مقدار بیشتر کن",ask(),{"last_feature":"Extrude 6","feature_parameters":{"depth":"16 mm"}})
add("feature","v12_f11","Extrude 7 رو suppress کن",do("feature.patch",{"feature_name":"Extrude 7","suppressed":True}))
add("feature","v12_f12","Extrude 7 رو برگردون روشن",do("feature.patch",{"feature_name":"Extrude 7","suppressed":False}))
add("feature","v12_f13","اسم Fillet 8 بشه soft corner",do("feature.patch",{"feature_name":"Fillet 8","new_name":"soft corner"}))
add("feature","v12_f14","Fillet 9 رو حذف کن",do("feature.delete",{"feature_name":"Fillet 9"}))
add("feature","v12_f15","آخرین آیتم درخت فیچر رو پاک کن",do("feature.delete",{"position":"last"}))
add("feature","v12_f16","اولین feature رو بنداز دور",do("feature.delete",{"position":"first"}))
add("feature","v12_f17","flip direction برای Extrude 2 رو true کن",do("feature.parameter.set",{"feature_name":"Extrude 2","parameter":"flip direction","value":True}))
add("feature","v12_f18","flip direction برای Draft 2 رو روشن کن",ask())

# parts/meta 14
add("part","v12_p01","Part 5 رو از نما بردار",do("part.visibility",{"part_name":"Part 5","visible":False}))
add("part","v12_p02","Part 5 دیگه دیده نشه",do("part.visibility",{"part_name":"Part 5","visible":False}))
add("part","v12_p03","همون پارت رو دوباره بیار توی نما",do("part.visibility",{"part_name":"Part 5","visible":True}),{"last_part":"Part 5","last_action":"hide"})
add("part","v12_p04","Bracket رو show کن",do("part.visibility",{"part_name":"Bracket","visible":True}))
add("part","v12_p05","Part 3 رو زرد کن",do("metadata.property.set",{"part_name":"Part 3","property":"color","value":"yellow"}))
add("part","v12_p06","Bracket رو سیاه کن",do("metadata.property.set",{"part_name":"Bracket","property":"color","value":"black"}))
add("part","v12_p07","اسم Part 7 بشه inner frame",do("metadata.property.set",{"part_name":"Part 7","property":"name","value":"inner frame"}))
add("part","v12_p08","متریال Part 4 رو آلومینیوم کن",do("metadata.property.set",{"part_name":"Part 4","property":"material","value":"Aluminum"}))
add("part","v12_p09","Part 6 رو فولاد متریال بده",do("metadata.property.set",{"part_name":"Part 6","property":"material","value":"Steel"}))
add("part","v12_p10","description Part 7 رو بذار frame trial",do("metadata.property.set",{"part_name":"Part 7","property":"description","value":"frame trial"}))
add("part","v12_p11","Part 10 رو حذف کن",do("feature.delete_part",{"part_name":"Part 10"}))
add("part","v12_p12","همین پارت آخری رو پاک کن",do("feature.delete_part",{"part_name":"Part 11"}),{"last_part":"Part 11"})
add("part","v12_p13","Part 3 رو قرمز کن و مخفیش کن",ask())
add("part","v12_p14","اسم همین پارت رو عوض کن",ask(),{"last_part":"Part 3"})

# create/order/document 12
add("doc","v12_d01","یه صفحه مرجع خالی درست کن",do("feature.add",{"feature_type":"plane"}))
add("doc","v12_d02","یه plane بساز با اسم datum bottom",do("feature.add",{"feature_type":"plane","name":"datum bottom"}))
add("doc","v12_d03","روی Right یه plane بساز",ask())
add("doc","v12_d04","Part 4 رو linear pattern پنج تایی با فاصله نه میل کن",do("feature.add",{"feature_type":"linearPattern","part_name":"Part 4","copies":5,"distance":"9 mm"}))
add("doc","v12_d05","از Part 3 سه تا pattern با فاصله شش و نیم میل بساز",do("feature.add",{"feature_type":"linearPattern","part_name":"Part 3","copies":3,"distance":"6.5 mm"}))
add("doc","v12_d06","Part 4 رو پنج نسخه کن هر نه میل",ask())
add("doc","v12_d07","Fillet 4 رو بالای Extrude 7 ببر",do("feature.reorder",{"source_feature":"Fillet 4","target_feature":"Extrude 7","placement":"before"}))
add("doc","v12_d08","Extrude 7 رو بعد Sketch 5 بذار",do("feature.reorder",{"source_feature":"Extrude 7","target_feature":"Sketch 5","placement":"after"}))
add("doc","v12_d09","rollback رو قبل Draft 2 بذار",do("rollback.set",{"before_feature":"Draft 2"}))
add("doc","v12_d10","rollback رو بذار اول",do("rollback.set",{"position":"start"}))
add("doc","v12_d11","یه Part Studio جدید به اسم fit shell بساز",do("documented.createPartStudio",{"new_name":"fit shell"}))
add("doc","v12_d12","rename document to case archive",do("documented.updateDocumentAttributes",{"new_name":"case archive"}))

# design/ambiguity/unsupported 10
add("escalate","v12_x01","طراحی رو یه کم حرفه ای تر و مرتب تر کن",think())
add("escalate","v12_x02","جوری تغییرش بده که برای تزریق بهتر باشه",think())
add("escalate","v12_x03","سبکش کن ولی استحکامش حفظ شه",think())
add("escalate","v12_x04","درخت فیچر رو خلوت و منطقی کن",think())
add("escalate","v12_x05","اون یکی رو پاک کن",ask())
add("escalate","v12_x06","دو میلش کن",ask())
add("escalate","v12_x07","همون عملیات قبلی رو روی اینم بزن",ask())
add("escalate","v12_x08","یه STEP ازش خروجی بگیر",ask())
add("escalate","v12_x09","با بقیه share کن",ask())
add("escalate","v12_x10","این document رو public کن",ask())

assert len(CASES)==100, len(CASES)
