plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.najme.shenavatest'
    compileSdk 35

    defaultConfig {
        applicationId 'com.najme.shenavatest'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    androidResources {
        noCompress += ['onnx', 'txt']
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    implementation files('libs/sherpa-onnx-1.13.8.aar')
}
