CASES=[]

def add(cat,cid,text,expected,ctx=None):
    CASES.append({"category":cat,"id":cid,"text":text,"ctx":ctx or {},"expected":expected if isinstance(expected,list) else [expected]})
def do(op,args=None): return {"route":"do","op":op,"args":args or {}}
def ask(): return {"route":"ask"}
def think(): return {"route":"think"}

# camera/viewer 16
add("camera","v13_c01","مدل رو یه ذره به چپ بچرخون",do("view.move",{"action":"orbit","direction":"left"}))
add("camera","v13_c02","به راست یکم rotate کن",do("view.move",{"action":"orbit","direction":"right"}))
add("camera","v13_c03","سی درجه ساعتگرد بچرخون",do("view.move",{"action":"orbit","direction":"clockwise","angle_degrees":30}))
add("camera","v13_c04","خلاف جهت عقربه یه کم بچرخ",do("view.move",{"action":"orbit","direction":"counterclockwise"}))
add("camera","v13_c05","نما رو هل بده راست",do("view.move",{"action":"pan","direction":"right"}))
add("camera","v13_c06","صفحه رو بکش پایین",do("view.move",{"action":"pan","direction":"down"}))
add("camera","v13_c07","یه کم نزدیک تر شو",do("view.move",{"action":"zoom","direction":"in"}))
add("camera","v13_c08","از مدل یه کم دورتر شو",do("view.move",{"action":"zoom","direction":"out"}))
add("camera","v13_c09","همه اش توی کادر جا بشه",do("view.fit",{"action":"fit"}))
add("camera","v13_c10","انتخاب فعلی رو تو کادر جا بده",do("view.fit",{"action":"fit_selection"}),{"selection_count":3,"selection_types":["edge","edge","face"]})
add("camera","v13_c11","از بالا نگاهش کن",do("view.standard",{"view":"top"}))
add("camera","v13_c12","انتخاب ها رو ول کن",do("viewer.selection.clear",{}))
add("camera","v13_c13","همون طرف بیشتر",do("view.move",{"action":"orbit","direction":"left"}),{"last_move":{"action":"orbit","direction":"left"}})
add("camera","v13_c14","زیادی شد، برگرد",do("view.move",{"action":"zoom","direction":"out"}),{"last_move":{"action":"zoom","direction":"in"}})
add("camera","v13_c15","نمای ایزومتریک بده",ask())
add("camera","v13_c16","نمای روبرو رو بیار",ask())

# inspect/follow 10
add("inspect","v13_i01","الان تو دستم چیه؟",do("viewer.inspect",{"mode":"selection"}))
add("inspect","v13_i02","چی رو الان سلکت کردم؟",do("viewer.inspect",{"mode":"selection"}))
add("inspect","v13_i03","وضعیت صفحه چطوره؟",do("viewer.inspect",{"mode":"state"}))
add("inspect","v13_i04","کیا الان وصلن؟",do("viewer.inspect",{"mode":"collaboration"}))
add("inspect","v13_i05","چند نفریم توی سشن؟",do("viewer.inspect",{"mode":"collaboration"}))
add("inspect","v13_i06","همکار روبرو رو follow کن",do("view.follow",{}),{"collaborator_count":2})
add("inspect","v13_i07","دومی رو دنبال کن",do("view.follow",{"candidate_index":2}),{"collaborator_count":3})
add("inspect","v13_i08","یکی از این چهار نفر رو دنبال کن",ask(),{"collaborator_count":4})
add("inspect","v13_i09","این face رو انتخاب کن",ask())
add("inspect","v13_i10","بگو selection فعلی چیه",do("viewer.inspect",{"mode":"selection"}))

# edge work 18
add("edge","v13_e01","لبه های انتخاب شده رو یک و هفت دهم میلی فیلت کن",do("feature.from_selection",{"feature_type":"fillet","amount":"1.7 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v13_e02","روی این انتخاب پخ هفتاد و پنج صدم میل بزن",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.75 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v13_e03","همین edge ها رو نیم میل گرد کن",do("feature.from_selection",{"feature_type":"fillet","amount":"0.5 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v13_e04","روی این لبه 2.2 mm chamfer بزن",do("feature.from_selection",{"feature_type":"chamfer","amount":"2.2 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v13_e05","فیلت یک میل و نیم روی این دوتا لبه",do("feature.from_selection",{"feature_type":"fillet","amount":"1.5 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v13_e06","پخ دو و دو دهم میلی روی انتخاب",do("feature.from_selection",{"feature_type":"chamfer","amount":"2.2 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v13_e07","یک و نیم میل فیلت کن",ask(),{"selection_count":0})
add("edge","v13_e08","روی همین انتخاب فیلت بزن",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v13_e09","یه fillet جدید هشت دهم میل بدون انتخاب بساز",do("feature.add",{"feature_type":"fillet","amount":"0.8 mm"}))
add("edge","v13_e10","یه chamfer خالی یک و یک دهم میلی بساز",do("feature.add",{"feature_type":"chamfer","amount":"1.1 mm"}))
add("edge","v13_e11","روی این لبه اول فیلت بزن بعد پخ",ask(),{"selection_count":1,"selection_types":["edge"]})
add("edge","v13_e12","فیلتش کن و رنگش رو هم آبی کن",ask(),{"selection_count":1,"selection_types":["edge"],"last_part":"Part 2"})
add("edge","v13_e13","radius دو میل روی انتخاب بده",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v13_e14","فیلت سه",ask(),{"selection_count":1,"selection_types":["edge"]})
add("edge","v13_e15","روی این edge ها سی و پنج صدم میل فیلت کن",do("feature.from_selection",{"feature_type":"fillet","amount":"0.35 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v13_e16","همین لبه رو ۰.۴ میلی پخ کن",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.4 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v13_e17","روی انتخاب فیلت یک و بیست صدم میل بزن",do("feature.from_selection",{"feature_type":"fillet","amount":"1.2 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v13_e18","یه fillet جدید 0.75 mm بدون انتخاب درست کن",do("feature.add",{"feature_type":"fillet","amount":"0.75 mm"}))

# feature edits 18
add("feature","v13_f01","شعاع Fillet 6 رو چهار و نیم میل کن",do("feature.parameter.set",{"feature_name":"Fillet 6","parameter":"radius","amount":"4.5 mm"}))
add("feature","v13_f02","depth Extrude 3 رو دوازده و نیم میل کن",do("feature.parameter.set",{"feature_name":"Extrude 3","parameter":"depth","amount":"12.5 mm"}))
add("feature","v13_f03","Extrude 3 رو دوازده میل کن",ask())
add("feature","v13_f04","Draft 5 رو دوازده درجه کن",do("feature.parameter.set",{"feature_name":"Draft 5","parameter":"angle","amount":"12 deg"}))
add("feature","v13_f05","angle Extrude 3 رو ده درجه کن",ask())
add("feature","v13_f06","عمق Draft 5 رو هفت میل کن",ask())
add("feature","v13_f07","depth Fillet 6 رو سه میل کن",ask())
add("feature","v13_f08","این فیلت رو هفتاد و پنج صدم میل بیشتر کن",do("feature.parameter.set",{"feature_name":"Fillet 6","parameter":"radius","amount":"4.75 mm"}),{"last_feature":"Fillet 6","feature_parameters":{"radius":"4 mm"}})
add("feature","v13_f09","این فیلت رو یک و دو دهم میل کمتر کن",do("feature.parameter.set",{"feature_name":"Fillet 6","parameter":"radius","amount":"2.8 mm"}),{"last_feature":"Fillet 6","feature_parameters":{"radius":"4 mm"}})
add("feature","v13_f10","این اکسترود رو دو میل بیشتر کن",ask(),{"last_feature":"Extrude 3","feature_parameters":{"depth":"12 mm"}})
add("feature","v13_f11","Extrude 10 رو خاموش کن",do("feature.patch",{"feature_name":"Extrude 10","suppressed":True}))
add("feature","v13_f12","Extrude 10 رو دوباره روشنش کن",do("feature.patch",{"feature_name":"Extrude 10","suppressed":False}))
add("feature","v13_f13","اسم Fillet 3 بشه hide fit corner",do("feature.patch",{"feature_name":"Fillet 3","new_name":"hide fit corner"}))
add("feature","v13_f14","Extrude 11 رو بنداز دور",do("feature.delete",{"feature_name":"Extrude 11"}))
add("feature","v13_f15","آخرین فیچر رو حذف کن",do("feature.delete",{"position":"last"}))
add("feature","v13_f16","اولین مورد درخت feature رو پاک کن",do("feature.delete",{"position":"first"}))
add("feature","v13_f17","flip direction برای Extrude 4 رو false کن",do("feature.parameter.set",{"feature_name":"Extrude 4","parameter":"flip direction","value":False}))
add("feature","v13_f18","flip direction برای Draft 4 رو true کن",ask())

# parts/meta 16
add("part","v13_p01","Cap رو از توی نما بردار",do("part.visibility",{"part_name":"Cap","visible":False}))
add("part","v13_p02","همون رو برگردون توی نما",do("part.visibility",{"part_name":"Cap","visible":True}),{"last_part":"Cap","last_action":"hide"})
add("part","v13_p03","Bracket دوباره دیده بشه",do("part.visibility",{"part_name":"Bracket","visible":True}))
add("part","v13_p04","Part 8 رو قرمز کن",do("metadata.property.set",{"part_name":"Part 8","property":"color","value":"red"}))
add("part","v13_p05","Cap رو خاکستری کن",do("metadata.property.set",{"part_name":"Cap","property":"color","value":"gray"}))
add("part","v13_p06","اسم Part 9 بشه fit hide shell",do("metadata.property.set",{"part_name":"Part 9","property":"name","value":"fit hide shell"}))
add("part","v13_p07","material Part 2 رو Steel بذار",do("metadata.property.set",{"part_name":"Part 2","property":"material","value":"Steel"}))
add("part","v13_p08","متریال Part 3 رو آلومینیوم کن",do("metadata.property.set",{"part_name":"Part 3","property":"material","value":"Aluminum"}))
add("part","v13_p09","Part 5 description بذار hide fit fillet",do("metadata.property.set",{"part_name":"Part 5","property":"description","value":"hide fit fillet"}))
add("part","v13_p10","Bracket رو پاک کن",do("feature.delete_part",{"part_name":"Bracket"}))
add("part","v13_p11","همون پارت رو حذف کن",do("feature.delete_part",{"part_name":"Part 12"}),{"last_part":"Part 12"})
add("part","v13_p12","Part 4 رو آبی کن و مخفیش کن",ask())
add("part","v13_p13","اسم Part 2 رو عوض کن",ask())
add("part","v13_p14","Part 2 رو مخفی کن با اسم spare shell",ask())
add("part","v13_p15","material Part 8 رو Titanium بذار",do("metadata.property.set",{"part_name":"Part 8","property":"material","value":"Titanium"}))
add("part","v13_p16","توضیحات Part 9 رو بذار fit ready",do("metadata.property.set",{"part_name":"Part 9","property":"description","value":"fit ready"}))

# create/order/document 12
add("doc","v13_d01","یه plane خالی تازه بساز",do("feature.add",{"feature_type":"plane"}))
add("doc","v13_d02","یه صفحه مرجع بساز به اسم datum side",do("feature.add",{"feature_type":"plane","name":"datum side"}))
add("doc","v13_d03","یه plane بساز با اسم hide fit top",do("feature.add",{"feature_type":"plane","name":"hide fit top"}))
add("doc","v13_d04","روی Front یه صفحه مرجع بساز",ask())
add("doc","v13_d05","Part 2 رو چهار تایی pattern کن با فاصله هفت میل",do("feature.add",{"feature_type":"linearPattern","part_name":"Part 2","copies":4,"distance":"7 mm"}))
add("doc","v13_d06","از Part 8 شش تا الگو با فاصله سه و نیم میل بساز",do("feature.add",{"feature_type":"linearPattern","part_name":"Part 8","copies":6,"distance":"3.5 mm"}))
add("doc","v13_d07","Part 2 رو چند نسخه با فاصله هفت میل بساز",ask())
add("doc","v13_d08","Sketch 7 رو قبل Extrude 9 ببر",do("feature.reorder",{"source_feature":"Sketch 7","target_feature":"Extrude 9","placement":"before"}))
add("doc","v13_d09","Fillet 2 رو بعد Draft 6 بذار",do("feature.reorder",{"source_feature":"Fillet 2","target_feature":"Draft 6","placement":"after"}))
add("doc","v13_d10","rollback رو بعد Extrude 5 بذار",do("rollback.set",{"after_feature":"Extrude 5"}))
add("doc","v13_d11","یه Part Studio تازه به اسم hide fit studio بساز",do("documented.createPartStudio",{"new_name":"hide fit studio"}))
add("doc","v13_d12","rename document to top fit archive",do("documented.updateDocumentAttributes",{"new_name":"top fit archive"}))

# design/ambiguity/unsupported 10
add("escalate","v13_x01","سبکش کن ولی سفتی قطعه کم نشه",think())
add("escalate","v13_x02","ظاهرش رو حرفه ای تر و تمیزتر کن",think())
add("escalate","v13_x03","درخت feature رو مرتب و خلوت کن",think())
add("escalate","v13_x04","برای قالب گیری تزریقی منطقی ترش کن",think())
add("escalate","v13_x05","اون آخریه رو پاک کن",ask())
add("escalate","v13_x06","سه میلش کن",ask())
add("escalate","v13_x07","همون کاری که قبلا کردی اینجا هم بزن",ask())
add("escalate","v13_x08","فایل STEP بده",ask())
add("escalate","v13_x09","این رو با تیم share کن",ask())
add("escalate","v13_x10","یه mirror ازش بساز",ask())

assert len(CASES)==100, len(CASES)
