CASES=[]

def add(cat,cid,text,expected,ctx=None):
    CASES.append({"category":cat,"id":cid,"text":text,"ctx":ctx or {},"expected":expected if isinstance(expected,list) else [expected]})
def do(op,args=None): return {"route":"do","op":op,"args":args or {}}
def ask(): return {"route":"ask"}
def think(): return {"route":"think"}

# camera/viewer 18
add("camera","v11_c01","مدل رو یه خرده سمت راست بچرخون",do("view.move",{"action":"orbit","direction":"right"}))
add("camera","v11_c02","یه کوچولو rotate left",do("view.move",{"action":"orbit","direction":"left"}))
add("camera","v11_c03","با جهت عقربه ساعت یه کم بچرخونش",do("view.move",{"action":"orbit","direction":"clockwise"}))
add("camera","v11_c04","خلاف جهت عقربه ساعت بچرخونش",do("view.move",{"action":"orbit","direction":"counterclockwise"}))
add("camera","v11_c05","چهل و پنج درجه به راست بچرخون",do("view.move",{"action":"orbit","direction":"right","angle_degrees":45}))
add("camera","v11_c06","ربع دور ببرش سمت چپ",do("view.move",{"action":"orbit","direction":"left","angle_degrees":90}))
add("camera","v11_c07","نما رو یه کم بکش بالا",do("view.move",{"action":"pan","direction":"up"}))
add("camera","v11_c08","صفحه رو یه کوچولو بکش پایین",do("view.move",{"action":"pan","direction":"down"}))
add("camera","v11_c09","pan right کن یه ذره",do("view.move",{"action":"pan","direction":"right"}))
add("camera","v11_c10","یه پله نزدیک تر شو",do("view.move",{"action":"zoom","direction":"in"}))
add("camera","v11_c11","یه پله دورتر شو",do("view.move",{"action":"zoom","direction":"out"}))
add("camera","v11_c12","کاری کن کل مدل معلوم باشه",do("view.fit",{"action":"fit"}))
add("camera","v11_c13","همین انتخاب بزرگ بشه تو صفحه",do("view.fit",{"action":"fit_selection"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("camera","v11_c14","نمای بالا رو نشون بده",do("view.standard",{"view":"top"}))
add("camera","v11_c15","هر چی انتخابه پاکش کن",do("viewer.selection.clear",{}))
add("camera","v11_c16","نمای جلو رو بیار",ask())
add("camera","v11_c17","نمای ایزومتریک بده",ask())
add("camera","v11_c18","یه کاری کن فقط انتخابم تو کادر باشه",do("view.fit",{"action":"fit_selection"}),{"selection_count":1,"selection_types":["face"]})

# inspect/follow 10
add("inspect","v11_i01","الان چی دستمه؟",do("viewer.inspect",{"mode":"selection"}))
add("inspect","v11_i02","ببین الان چی گرفتم",do("viewer.inspect",{"mode":"selection"}))
add("inspect","v11_i03","وضعیت صفحه رو یه نگاه بنداز",do("viewer.inspect",{"mode":"state"}))
add("inspect","v11_i04","ببین کیا الان وصلن",do("viewer.inspect",{"mode":"collaboration"}))
add("inspect","v11_i05","ببین توی session چند نفریم",do("viewer.inspect",{"mode":"collaboration"}))
add("inspect","v11_i06","طرف مقابلم رو follow کن",do("view.follow",{}),{"collaborator_count":2})
add("inspect","v11_i07","دومی رو فالو کن",do("view.follow",{"candidate_index":2}),{"collaborator_count":3})
add("inspect","v11_i08","یکی از این چند نفر رو فالو کن",ask(),{"collaborator_count":4})
add("inspect","v11_i09","همین سطحی که روشیم رو بگیر",ask())
add("inspect","v11_i10","اون لبه سمت چپی رو انتخاب کن",ask())

# edge work 18
add("edge","v11_e01","روی انتخاب فیلت یک و سه دهم میل بزن",do("feature.from_selection",{"feature_type":"fillet","amount":"1.3 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v11_e02","این لبه ها رو شصت و پنج صدم میل پخ کن",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.65 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v11_e03","همین لبه ها رو دو میل و نیم گرد کن",do("feature.from_selection",{"feature_type":"fillet","amount":"2.5 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v11_e04","روی همین انتخاب پخ یک ممیز هفت میل",do("feature.from_selection",{"feature_type":"chamfer","amount":"1.7 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v11_e05","فیلت سه و بیست صدم میلی روی اینا",do("feature.from_selection",{"feature_type":"fillet","amount":"3.2 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v11_e06","پخ چهار دهم روی انتخاب",do("feature.from_selection",{"feature_type":"chamfer","amount":"0.4 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v11_e07","روی این دو لبه ۱.۷۵ mm fillet بزن",do("feature.from_selection",{"feature_type":"fillet","amount":"1.75 mm"}),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v11_e08","فیلت نیم میل روی همین لبه",do("feature.from_selection",{"feature_type":"fillet","amount":"0.5 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v11_e09","دو میل پخ بزن",ask(),{"selection_count":0})
add("edge","v11_e10","این انتخاب رو فیلت کن",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v11_e11","یه fillet خالی سه و نیم میل بساز",do("feature.add",{"feature_type":"fillet","amount":"3.5 mm"}))
add("edge","v11_e12","یه پخ جدید هشت دهم میل بدون انتخاب بساز",do("feature.add",{"feature_type":"chamfer","amount":"0.8 mm"}))
add("edge","v11_e13","دو میل فیلت کن بعد یک میل پخ",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v11_e14","فیلتش کن و بعد مخفیش کن",ask(),{"selection_count":1,"selection_types":["edge"],"last_part":"Part 3"})
add("edge","v11_e15","روی انتخاب radius دو میل بده",ask(),{"selection_count":2,"selection_types":["edge","edge"]})
add("edge","v11_e16","فیلت دو",ask(),{"selection_count":1,"selection_types":["edge"]})
add("edge","v11_e17","پخ دو و نیم میل روی همین انتخاب",do("feature.from_selection",{"feature_type":"chamfer","amount":"2.5 mm"}),{"selection_count":1,"selection_types":["edge"]})
add("edge","v11_e18","یه chamfer خالی ۰.۳ میلی بساز",do("feature.add",{"feature_type":"chamfer","amount":"0.3 mm"}))

# feature edits 18
add("feature","v11_f01","شعاع Fillet 3 رو هفت میل کن",do("feature.parameter.set",{"feature_name":"Fillet 3","parameter":"radius","amount":"7 mm"}))
add("feature","v11_f02","عمق Extrude 2 رو هجده میل بذار",do("feature.parameter.set",{"feature_name":"Extrude 2","parameter":"depth","amount":"18 mm"}))
add("feature","v11_f03","Extrude 2 رو هجده میل کن",ask())
add("feature","v11_f04","زاویه Draft 2 رو هفت درجه کن",do("feature.parameter.set",{"feature_name":"Draft 2","parameter":"angle","amount":"7 deg"}))
add("feature","v11_f05","این فیلت رو یک و سه دهم میل بیشتر کن",do("feature.parameter.set",{"feature_name":"Fillet 2","parameter":"radius","amount":"5.3 mm"}),{"last_feature":"Fillet 2","feature_parameters":{"radius":"4 mm"}})
add("feature","v11_f06","این فیلت رو هفتاد و پنج صدم میل کمتر کن",do("feature.parameter.set",{"feature_name":"Fillet 2","parameter":"radius","amount":"3.25 mm"}),{"last_feature":"Fillet 2","feature_parameters":{"radius":"4 mm"}})
add("feature","v11_f07","یه کم بیشترش کن",ask(),{"last_feature":"Extrude 2","feature_parameters":{"depth":"12 mm"}})
add("feature","v11_f08","Extrude 5 رو خاموش کن",do("feature.patch",{"feature_name":"Extrude 5","suppressed":True}))
add("feature","v11_f09","Extrude 5 رو دوباره روشن کن",do("feature.patch",{"feature_name":"Extrude 5","suppressed":False}))
add("feature","v11_f10","برش گردون",do("feature.patch",{"feature_name":"Extrude 5","suppressed":False}),{"last_feature":"Extrude 5","last_action":"suppress"})
add("feature","v11_f11","اسم Fillet 6 بشه smooth rim",do("feature.patch",{"feature_name":"Fillet 6","new_name":"smooth rim"}))
add("feature","v11_f12","Fillet 7 رو بنداز دور",do("feature.delete",{"feature_name":"Fillet 7"}))
add("feature","v11_f13","آخرین چیزی که توی درخت فیچر ساختیم رو پاک کن",do("feature.delete",{"position":"last"}))
add("feature","v11_f14","اولین فیچر رو حذف کن",do("feature.delete",{"position":"first"}))
add("feature","v11_f15","flip direction برای Extrude 4 رو روشن کن",do("feature.parameter.set",{"feature_name":"Extrude 4","parameter":"flip direction","value":True}))
add("feature","v11_f16","flip direction برای Extrude 4 رو off کن",do("feature.parameter.set",{"feature_name":"Extrude 4","parameter":"flip direction","value":False}))
add("feature","v11_f17","شعاع همین فیلت رو دو میل کن",do("feature.parameter.set",{"feature_name":"Fillet 4","parameter":"radius","amount":"2 mm"}),{"last_feature":"Fillet 4"})
add("feature","v11_f18","زاویه اش رو پنج درجه کن",ask(),{"last_feature":"Extrude 4"})

# parts/meta 14
add("part","v11_p01","Part 4 رو از جلوی چشم بردار",do("part.visibility",{"part_name":"Part 4","visible":False}))
add("part","v11_p02","Part 4 دیگه دیده نشه",do("part.visibility",{"part_name":"Part 4","visible":False}))
add("part","v11_p03","همون پارت رو برگردون تو نما",do("part.visibility",{"part_name":"Part 4","visible":True}),{"last_part":"Part 4","last_action":"hide"})
add("part","v11_p04","Cap رو نشون بده",do("part.visibility",{"part_name":"Cap","visible":True}))
add("part","v11_p05","Part 2 رو قرمز کن",do("metadata.property.set",{"part_name":"Part 2","property":"color","value":"red"}))
add("part","v11_p06","Cap رو خاکستری کن",do("metadata.property.set",{"part_name":"Cap","property":"color","value":"gray"}))
add("part","v11_p07","اسم Part 5 بشه cover plate",do("metadata.property.set",{"part_name":"Part 5","property":"name","value":"cover plate"}))
add("part","v11_p08","متریال Part 3 رو فولاد کن",do("metadata.property.set",{"part_name":"Part 3","property":"material","value":"Steel"}))
add("part","v11_p09","Part 6 رو آلومینیوم متریال بده",do("metadata.property.set",{"part_name":"Part 6","property":"material","value":"Aluminum"}))
add("part","v11_p10","description Part 2 رو بذار inner shell",do("metadata.property.set",{"part_name":"Part 2","property":"description","value":"inner shell"}))
add("part","v11_p11","Part 8 رو پاک کن",do("feature.delete_part",{"part_name":"Part 8"}))
add("part","v11_p12","همین پارت رو حذف کن",do("feature.delete_part",{"part_name":"Part 9"}),{"last_part":"Part 9"})
add("part","v11_p13","Part 2 رو آبی کن و قایمش کن",ask())
add("part","v11_p14","اسم همین پارت رو عوض کن",ask(),{"last_part":"Part 2"})

# create/order/document 12
add("doc","v11_d01","یه plane خالی بساز",do("feature.add",{"feature_type":"plane"}))
add("doc","v11_d02","یه صفحه مرجع بساز اسمش datum rear",do("feature.add",{"feature_type":"plane","name":"datum rear"}))
add("doc","v11_d03","یه plane روی Front بساز",ask())
add("doc","v11_d04","از Part 2 یه linear pattern چهار تایی با فاصله یازده میل بساز",do("feature.add",{"feature_type":"linearPattern","part_name":"Part 2","copies":4,"distance":"11 mm"}))
add("doc","v11_d05","Part 3 رو سه تا pattern کن با فاصله هفت و نیم میل",do("feature.add",{"feature_type":"linearPattern","part_name":"Part 3","copies":3,"distance":"7.5 mm"}))
add("doc","v11_d06","Part 2 رو چهار تا کن هر یازده میل",ask())
add("doc","v11_d07","Fillet 2 رو قبل Extrude 5 ببر",do("feature.reorder",{"source_feature":"Fillet 2","target_feature":"Extrude 5","placement":"before"}))
add("doc","v11_d08","Extrude 4 رو زیر Sketch 3 بنداز",do("feature.reorder",{"source_feature":"Extrude 4","target_feature":"Sketch 3","placement":"after"}))
add("doc","v11_d09","rollback رو قبل Fillet 3 بذار",do("rollback.set",{"before_feature":"Fillet 3"}))
add("doc","v11_d10","rollback رو ببر آخر",do("rollback.set",{"position":"end"}))
add("doc","v11_d11","یه Part Studio جدید به اسم shell trial بساز",do("documented.createPartStudio",{"new_name":"shell trial"}))
add("doc","v11_d12","اسم document بشه case final",do("documented.updateDocumentAttributes",{"new_name":"case final"}))

# design / ambiguity / unsupported 10
add("escalate","v11_x01","این طراحی رو حرفه ای تر و تمیزتر کن",think())
add("escalate","v11_x02","جوری تغییرش بده برای تزریق منطقی تر باشه",think())
add("escalate","v11_x03","وزنش کمتر شه ولی استحکامش نریزه",think())
add("escalate","v11_x04","درخت فیچر رو مرتب و خلوت کن",think())
add("escalate","v11_x05","اون یکی رو حذف کن",ask())
add("escalate","v11_x06","سه میلش کن",ask())
add("escalate","v11_x07","همون کار قبلی رو اینجا هم انجام بده",ask())
add("escalate","v11_x08","ازش STEP بگیر",ask())
add("escalate","v11_x09","با تیم share کن",ask())
add("escalate","v11_x10","همه بتونن ببیننش publicش کن",ask())

assert len(CASES)==100, len(CASES)
