CASES = []

def add(category, cid, text, expected, ctx=None):
    CASES.append({"category":category,"id":cid,"text":text,"ctx":ctx or {},"expected":expected if isinstance(expected,list) else [expected]})

def do(op, args=None):
    return {"route":"do","op":op,"args":args or {}}

def ask():
    return {"route":"ask"}

def think():
    return {"route":"think"}

add('camera', 'syn_cam_01', 'یه خرده بچرخونش طرف راست', do('view.move', {'action': 'orbit', 'direction': 'right'}))
add('camera', 'syn_cam_02', 'مدلو یه کم بیار سمت چپ', do('view.move', {'action': 'orbit', 'direction': 'left'}))
add('camera', 'syn_cam_03', 'یه کوچولو ساعتگردش کن', do('view.move', {'action': 'orbit', 'direction': 'clockwise'}))
add('camera', 'syn_cam_04', 'پادساعتگرد یه ذره', do('view.move', {'action': 'orbit', 'direction': 'counterclockwise'}))
add('camera', 'syn_cam_05', 'یه ربع دور به راست بچرخون', do('view.move', {'action': 'orbit', 'direction': 'right', 'angle_degrees': 90}))
add('camera', 'syn_cam_06', 'باز یه ذره همون طرف', do('view.move', {'action': 'orbit', 'direction': 'right'}), {'last_move': {'action': 'orbit', 'direction': 'right', 'intensity': 0.3}})
add('camera', 'syn_cam_07', 'نه، زیادی شد یه کم برش گردون', do('view.move', {'action': 'orbit', 'direction': 'left'}), {'last_move': {'action': 'orbit', 'direction': 'right', 'intensity': 0.8}})
add('camera', 'syn_cam_08', 'نما رو یه کم هل بده راست', do('view.move', {'action': 'pan', 'direction': 'right'}))
add('camera', 'syn_cam_09', 'یه ذره صفحه رو ببر بالا', do('view.move', {'action': 'pan', 'direction': 'up'}))
add('camera', 'syn_cam_10', 'همون پن رو یه کم بیشتر کن', do('view.move', {'action': 'pan', 'direction': 'up'}), {'last_move': {'action': 'pan', 'direction': 'up', 'intensity': 0.2}})
add('camera', 'syn_cam_11', 'زومشو یه کوچولو بیشتر کن', do('view.move', {'action': 'zoom', 'direction': 'in'}), {'last_move': {'action': 'zoom', 'direction': 'in', 'intensity': 0.25}})
add('camera', 'syn_cam_12', 'یکم عقب\u200cتر برو', do('view.move', {'action': 'zoom', 'direction': 'out'}), {'last_move': {'action': 'zoom', 'direction': 'in', 'intensity': 0.4}})
add('camera', 'syn_cam_13', 'کل مدل تو کادر جا بشه', do('view.fit', {'action': 'fit'}))
add('camera', 'syn_cam_14', 'فقط روی همین انتخاب فیتش کن', do('view.fit', {'action': 'fit_selection'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('camera', 'syn_cam_15', 'از بالا نگاهش کن', do('view.standard', {'view': 'top'}))
add('camera', 'syn_cam_16', 'انتخابارو ول کن', do('viewer.selection.clear', {}))
add('camera', 'syn_cam_17', 'یه نمای روبرو بده', ask())
add('camera', 'syn_cam_18', 'ایزو بده', ask())

add('inspect_follow', 'syn_ins_01', 'الان دقیقاً چی انتخابه؟', do('viewer.inspect', {'mode': 'selection'}))
add('inspect_follow', 'syn_ins_02', 'یه نگاه کن وضعیت ویور چیه', do('viewer.inspect', {'mode': 'state'}))
add('inspect_follow', 'syn_ins_03', 'ببین الان چند نفر تو این سشنیم', do('viewer.inspect', {'mode': 'collaboration'}))
add('inspect_follow', 'syn_ins_04', 'اون یکی کاربر رو فالو کن', do('view.follow', {}), {'collaborator_count': 2})
add('inspect_follow', 'syn_ins_05', 'نفر دوم رو بگیر فالو', do('view.follow', {'candidate_index': 2}), {'collaborator_count': 3})
add('inspect_follow', 'syn_ins_06', 'یکی از اون دوتا رو فالو کن', ask(), {'collaborator_count': 3})
add('inspect_follow', 'syn_ins_07', 'این یکی رو انتخاب کن', ask(), {'selection_count': 0})
add('inspect_follow', 'syn_ins_08', 'اون لبه کناری رو هم اضافه کن به انتخاب', ask(), {'selection_count': 1})

add('from_selection', 'syn_sel_01', 'روی همین دوتا لبه یه فیلت دو میل بزن', do('feature.from_selection', {'feature_type': 'fillet', 'amount': '2 mm'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_02', 'این دوتا رو یه میل پخ بزن', do('feature.from_selection', {'feature_type': 'chamfer', 'amount': '1 mm'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_03', 'لبه\u200cهایی که انتخاب کردم رو یک و نیم میل چمفر کن', do('feature.from_selection', {'feature_type': 'chamfer', 'amount': '1.5 mm'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_04', 'روی انتخاب فعلی فیلت نیم میل', do('feature.from_selection', {'feature_type': 'fillet', 'amount': '0.5 mm'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_05', 'همینارو پخ بزن، دو میل', do('feature.from_selection', {'feature_type': 'chamfer', 'amount': '2 mm'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_06', 'لبه\u200cها رو fillet دو و نیم میل', do('feature.from_selection', {'feature_type': 'fillet', 'amount': '2.5 mm'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_07', 'پخ هشت دهم روی همینا', do('feature.from_selection', {'feature_type': 'chamfer', 'amount': '0.8 mm'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_08', 'این انتخاب رو فیلت کن', ask(), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_09', 'یه میل پخ بزن', ask(), {'selection_count': 0})
add('from_selection', 'syn_sel_10', 'این دوتا رو سه میل گرد کن', ask(), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_11', 'همین دوتا دو و نیم میل فیلت', do('feature.from_selection', {'feature_type': 'fillet', 'amount': '2.5 mm'}), {'selection_count': 2, 'selection_types': ['edge', 'edge']})
add('from_selection', 'syn_sel_12', 'این دوتا رو دو میل فیلت و بعد یه میل پخ بزن', ask(), {'selection_count': 2, 'selection_types': ['edge', 'edge']})

add('feature_edit', 'syn_feat_01', 'فیلت سه رو ببر روی شش میل', do('feature.parameter.set', {'feature_name': 'Fillet 3', 'parameter': 'radius', 'amount': '6 mm'}))
add('feature_edit', 'syn_feat_02', 'عمق اکسترود چهار رو هجده میل کن', do('feature.parameter.set', {'feature_name': 'Extrude 4', 'parameter': 'depth', 'amount': '18 mm'}))
add('feature_edit', 'syn_feat_03', 'Extrude 4 رو بکن هجده میل', do('feature.parameter.set', {'feature_name': 'Extrude 4', 'parameter': 'depth', 'amount': '18 mm'}))
add('feature_edit', 'syn_feat_04', 'Draft 2 زاویه\u200cش بشه هفت درجه', do('feature.parameter.set', {'feature_name': 'Draft 2', 'parameter': 'angle', 'amount': '7 deg'}))
add('feature_edit', 'syn_feat_05', 'این فیلت رو چهار میل کن', do('feature.parameter.set', {'feature_name': 'Fillet 2', 'parameter': 'radius', 'amount': '4 mm'}), {'last_feature': 'Fillet 2'})
add('feature_edit', 'syn_feat_06', 'یه میل زیادش کن', do('feature.parameter.set', {'feature_name': 'Fillet 2', 'parameter': 'radius', 'amount': '4 mm'}), {'last_feature': 'Fillet 2', 'feature_parameters': {'radius': '3 mm'}})
add('feature_edit', 'syn_feat_07', 'خاموشش کن', do('feature.patch', {'feature_name': 'Extrude 2', 'suppressed': True}), {'last_feature': 'Extrude 2'})
add('feature_edit', 'syn_feat_08', 'برش گردون', do('feature.patch', {'feature_name': 'Extrude 2', 'suppressed': False}), {'last_feature': 'Extrude 2', 'last_action': 'suppress'})
add('feature_edit', 'syn_feat_09', 'اسم این فیلت رو بذار نرم\u200cکن', do('feature.patch', {'feature_name': 'Fillet 1', 'new_name': 'نرم\u200cکن'}), {'last_feature': 'Fillet 1'})
add('feature_edit', 'syn_feat_10', 'آخرین فیچرو بنداز دور', do('feature.delete', {'position': 'last'}))
add('feature_edit', 'syn_feat_11', 'فیلت پنج رو حذف کن', do('feature.delete', {'feature_name': 'Fillet 5'}))
add('feature_edit', 'syn_feat_12', 'پارت سه رو پاک کن', do('feature.delete_part', {'part_name': 'Part 3'}))
add('feature_edit', 'syn_feat_13', 'این پارته رو پاک کن', do('feature.delete_part', {'part_name': 'Part 2'}), {'last_part': 'Part 2'})
add('feature_edit', 'syn_feat_14', 'Extrude 2 رو یه کم بیشتر کن', ask(), {'last_feature': 'Extrude 2', 'feature_parameters': {'depth': '10 mm'}})

add('part_metadata', 'syn_part_01', 'Cap رو قایم کن', do('part.visibility', {'part_name': 'Cap', 'visible': False}))
add('part_metadata', 'syn_part_02', 'اون پارت قبلی رو دوباره بیار', do('part.visibility', {'part_name': 'Cap', 'visible': True}), {'last_part': 'Cap', 'last_action': 'hide'})
add('part_metadata', 'syn_part_03', 'Part 7 رو نشون نده', do('part.visibility', {'part_name': 'Part 7', 'visible': False}))
add('part_metadata', 'syn_part_04', 'Part 7 رو دیگه نشون نده', do('part.visibility', {'part_name': 'Part 7', 'visible': False}))
add('part_metadata', 'syn_part_05', 'رنگ این پارت رو مشکی کن', do('metadata.property.set', {'part_name': 'Part 2', 'property': 'color', 'value': 'black'}), {'last_part': 'Part 2'})
add('part_metadata', 'syn_part_06', 'Cap رو خاکستری کن', do('metadata.property.set', {'part_name': 'Cap', 'property': 'color', 'value': 'gray'}))
add('part_metadata', 'syn_part_07', 'اسم Part 3 رو بذار housing', do('metadata.property.set', {'part_name': 'Part 3', 'property': 'name', 'value': 'housing'}))
add('part_metadata', 'syn_part_08', 'Part 2 اسمش بشه lid', do('metadata.property.set', {'part_name': 'Part 2', 'property': 'name', 'value': 'lid'}))
add('part_metadata', 'syn_part_09', 'متریالش رو فولاد کن', do('metadata.property.set', {'part_name': 'Part 1', 'property': 'material', 'value': 'Steel'}), {'last_part': 'Part 1'})
add('part_metadata', 'syn_part_10', 'description اینو بذار test cover', do('metadata.property.set', {'part_name': 'Cap', 'property': 'description', 'value': 'test cover'}), {'last_part': 'Cap'})

add('feature_add', 'syn_add_01', 'یه plane بساز به اسم datum top', do('feature.add', {'feature_type': 'plane', 'name': 'datum top'}))
add('feature_add', 'syn_add_02', 'یه صفحه مرجع خالی بساز', do('feature.add', {'feature_type': 'plane'}))
add('feature_add', 'syn_add_03', 'از Part 2 یه pattern چهارتایی با گام پانزده میل بساز', do('feature.add', {'feature_type': 'linearPattern', 'part_name': 'Part 2', 'copies': 4, 'distance': '15 mm'}))
add('feature_add', 'syn_add_04', 'Part 3 رو شش تا، فاصله هشت میل، خطی تکرار کن', do('feature.add', {'feature_type': 'linearPattern', 'part_name': 'Part 3', 'copies': 6, 'distance': '8 mm'}))
add('feature_add', 'syn_add_05', 'Part 2 رو چهارتا کن هر پانزده میل', ask())
add('feature_add', 'syn_add_06', 'یه فیلت خالی پنج میل بنداز', do('feature.add', {'feature_type': 'fillet', 'amount': '5 mm'}))
add('feature_add', 'syn_add_07', 'یه پخ خالی سه میل بساز', do('feature.add', {'feature_type': 'chamfer', 'amount': '3 mm'}))
add('feature_add', 'syn_add_08', 'یه فیلت جدید بساز، فعلاً بدون لبه، دو میل', do('feature.add', {'feature_type': 'fillet', 'amount': '2 mm'}))
add('feature_add', 'syn_add_09', 'یه plane روی Top بساز', ask())
add('feature_add', 'syn_add_10', 'یه hole شش میل اینجا بزن', ask(), {'selection_count': 1, 'selection_types': ['face']})

add('document_order', 'syn_ord_01', 'Fillet 2 رو ببر بالای Extrude 4', do('feature.reorder', {'source_feature': 'Fillet 2', 'target_feature': 'Extrude 4', 'placement': 'before'}))
add('document_order', 'syn_ord_02', 'Extrude 5 رو بنداز زیر Sketch 2', do('feature.reorder', {'source_feature': 'Extrude 5', 'target_feature': 'Sketch 2', 'placement': 'after'}))
add('document_order', 'syn_ord_03', 'همینو ببر قبل Fillet 6', do('feature.reorder', {'source_feature': 'Extrude 2', 'target_feature': 'Fillet 6', 'placement': 'before'}), {'last_feature': 'Extrude 2'})
add('document_order', 'syn_ord_04', 'rollback رو بذار درست قبل Extrude 3', do('rollback.set', {'before_feature': 'Extrude 3'}))
add('document_order', 'syn_ord_05', 'rollback رو تا آخر بکش', do('rollback.set', {'position': 'end'}))
add('document_order', 'syn_ord_06', 'rollback رو اول کار بذار', do('rollback.set', {'position': 'start'}))
add('document_order', 'syn_ord_07', 'یه پارت استودیو بساز اسمش تست پوسته', do('documented.createPartStudio', {'new_name': 'تست پوسته'}))
add('document_order', 'syn_ord_08', 'یه tab جدید Part Studio بساز به اسم rough', do('documented.createPartStudio', {'new_name': 'rough'}))
add('document_order', 'syn_ord_09', 'اسم این داکیومنت بشه suitcase base', do('documented.updateDocumentAttributes', {'new_name': 'suitcase base'}))
add('document_order', 'syn_ord_10', 'داکیومنتو rename کن به rev B', do('documented.updateDocumentAttributes', {'new_name': 'rev B'}))

add('escalation', 'syn_esc_01', 'این رو یه کم حرفه\u200cای\u200cترش کن', think())
add('escalation', 'syn_esc_02', 'این گوشه\u200cها رو جوری درست کن که تولیدش راحت\u200cتر شه', think())
add('escalation', 'syn_esc_03', 'وزنشو کم کن ولی سفت بمونه', think())
add('escalation', 'syn_esc_04', 'همه فیچرهای اضافی رو پاک کن', think())
add('escalation', 'syn_esc_05', 'کل مدل رو حذف کن', ask())
add('escalation', 'syn_esc_06', 'اون یکی رو پاک کن', ask())
add('escalation', 'syn_esc_07', 'دو میلش کن', ask())
add('escalation', 'syn_esc_08', 'همین کارو برای اون یکی هم بکن', ask())
add('escalation', 'syn_esc_09', 'نمای روبرو', ask())
add('escalation', 'syn_esc_10', 'ازش STEP بگیر', ask())
add('escalation', 'syn_esc_11', 'این دوتا رو mate کن', ask())
add('escalation', 'syn_esc_12', 'share کن با فلانی', ask())
add('escalation', 'syn_esc_13', 'Part 1 رو قرمز کن و مخفیش کن', ask())
add('escalation', 'syn_esc_14', 'همه چی رو public کن', ask())

assert len(CASES) == 96, len(CASES)
